project:
  type: book
  output-dir: _book
  
book:
  title: "Heraclitus Ephesius"
  author: "SILVA, Martim"
  description: | 
    Um site de referência sobre o filósofo jônico Heráclito que floresceu durante o período arcaico.
  site-url: https://tutorials.thecoatlessprofessor.com/quarto-book-template
  repo-url: https://github.com/bcdavasconcelos/Heraclitus
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: my-first-book.qmd
      chapters: 
        - hello-world.qmd
  appendices:
    - appendix-notes.qmd
    
format:
  html: 
    theme: cosmo
    code-link: true
